### ISSUE TITLE
Model file broken after being "succesfully downloaded"

### ISSUE THREAD

**Issue by hakaserver** [sunnyark/civitai-shortcut#88] opened 2023-11-04 05:24 UTC
Some times, downloading a model through Civitai Shortcut fails. Even though the log says it was "successfully downloaded", the download process clearly finishes too quickly and the file fails to download.

The steps I usually take when downloading a model:

> Paste the link of a model page in the register model tab. [Example of model that fails to download here](https://civitai.com/models/186571/japanese-police-uniform-by-stable-yogi).
> Update classification information.
> Select folder location for download.
> Click Download button.
> The download finishes too quickly, but message says " successfully downloaded."
> Check downloaded file size to determine it only has ~100kb and failed to download.

Inspecting the file, it shows only 104kb independently of the original file size.
Pressing the download button again repeats the same occurrence and an additional ~100kb is added to the file each time it is downloaded again.
If the file is deleted before trying again, the download keeps failing.
Even if this happens, some models do not fail to download, while others keep failing.
It is not 100% clear if this is model dependant, but models that fail to download seems to keep failing, while others never do.

**Comment by k0ala991** [comment] 2023-11-22 03:46
I've experience this before as well on several models, and was able to reproduce the problem using the model linked above using the latest version.

**Comment by jim60105** [comment] 2024-02-11 18:49
Fixed in https://github.com/jim60105/civitai-shortcut

Not sure if I should submit a PR, since I just pick the code from [cratom4](https://github.com/cratom4/civitai-shortcut) and add the UI, and I saw the notice at top of the readme.

**Comment by jim60105** [comment] 2024-02-11 18:52
Please be aware that you have to fill the API key in the settings.
![image](https://github.com/sunnyark/civitai-shortcut/assets/16995691/a1d4259b-97d4-4243-95df-8fea1a00f25a)

**Closed** 2024-03-24 15:26 UTC
