### ISSUE TITLE
bug on register shortcut

### ISSUE THREAD

**Issue by chuckkay** [sunnyark/civitai-shortcut#77] opened 2023-09-02 01:54 UTC
drag and drop or copy and paste civitai lora shortcut and it loads but then endlessley shows processing and then cant add anymore urls unless you restart

**Comment by sunnyark** [comment] 2023-09-04 02:54
Is this issue occurring only in a specific model, or is it a common symptom across most models? If it's specific to a particular model, it could be due to the presence of multiple versions within that model. Alternatively, if there are delays in fetching data from Civitai, it might be attributed to the data retrieval process taking longer.

**Comment by fsilveiradev** [comment] 2023-09-04 04:15
This issue is occurring in any model, it is a common symptom and seems to occurr regardless if the models presents multiple versions within or not. This symptom started occurring to me exactly after updating a1111 from v1.5.2 to v1.6.0, so it might be due to a gradio update maybe? (some extensions started throwing gradio deprecation warnings)

Before updating a1111 and before pulling the latest extension commit, the register shortcut was working as intended.

```
version: [v1.6.0]  •  python: 3.10.6  •  torch: 2.0.0+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2 
civitai-shortcut | https://github.com/sunnyark/civitai-shortcut | main | 53c6755f | 2023-08-27 11:19:10 | latest
```

**Comment by sunnyark** [comment] 2023-09-04 04:38
The error was identified as a result of the recent update to Gradio in version a1111, which brought several changes. We apologize for any oversights in making the necessary adjustments. We will soon release an update to address this issue. Thank you for reporting it.

**Comment by fsilveiradev** [comment] 2023-09-04 05:08
Thanks for the update! Latest commit fixed on my end!

**Closed** 2023-09-04 05:39 UTC
